### ISSUE TITLE
npa extractor

### ISSUE THREAD

**Issue by fisch123456** [fffonion/npa-python#1]
If I understand corectly this tool can open npa files right?

**Comment by fffonion** [comment]
Yes correct.

**Comment by fisch123456** [comment]
Thanks for answer, probably don't know how to open npf files?Thanks

**Comment by fffonion** [comment]
Please read https://github.com/fffonion/npa-python/blob/master/README.md.

**Comment by fisch123456** [comment]
So it can open totono npf files?

**Comment by fffonion** [comment]
I think totono is not yet implemented (https://github.com/fffonion/npa-python/blob/master/npa.py#L632) as I don't have a sample on my side to test. But the alogrithm is there so you could probably test it with some translation from C to python.
